paths = [
    ['uurrDDDDuuuulldRurDDDrddLLrruLuuulldRurDDDrdL'],
    ['drrRRurDDDDDrdLLL'],
    ['rrdrUrrrdLLulDullldR'],
    ['lluRRdrUllluuurrDDuulldRurD'],
    ['urrrrdrruulullllDurrrrdrddllullLrrrdrruLLL'],
    ['uurrrrDulllddrrRuulDrdL'],
    ['drrdddrdLLLuLDlUUUluRRRRurDDD'],
    ['uullLLddrrUdlllluuRurDrRddrruuLLL'],
    ['lUlLLdlluururrrrDDrdLullldlluRRRRllluurrrrdD'],
    ['ddrddLLulLdlUrrrdrruuluulldDuurrddrddllLLrruLL'],
    ['luurrrdrdLLLrrrddlUruuulllldDrddlUUrrRdrU'],
    ['ddlluluRuurrrDrddlluLrdrruLLddlluU'],
    ['dddlluluuRDrruulDrdLLulDrDLurrrddlLL'],
    ['drrdDrrddllUUUUruLdrDldR', 'drrdDrrddllUUUUrDldRuuuL'],
    ['drruLLLuulldRurDurDD'],
    ['urRdddrrUULLulldRururrD'],
    ['uLrddlluluuRDrrruullDldRRdrUU'],
    ['dddlUllllddrUUddrrUruLLrrruulDrdLL'],
    ['llldlUUUluurDrrrDDrdLLLulUluRRlddrddlUUUluR'],
    ['ulldRurDrrddllUUluurrDLLdrddrruuLrddlluU'],
    ['ddrruuLLruulDDrrddlUUddllluuRRDullddrRurruLLuurDDlddlluuRlddrruUrrddL'],
]
